### ISSUE TITLE
Filenames that start with "#" fail

### ISSUE THREAD

**Issue by bexelbie** [thejambi/psnotes#3] opened 2017-01-04 20:34 UTC
File names that start with a # cause psnotes to try to go into a directory and result in the file being deleted.

I have a phone app that doesn't use markdown and can save files with names exactly like the first line.

**Comment by thejambi** [comment] 2017-01-05 01:47
I cannot reproduce the file getting deleted, but I know why it is thinking it is a folder. (Hidden features caused it. Sorry, I am switching the special characters used to a '/' instead, so this shouldn't happen any more. Will be fixed tonight.)

**Comment by thejambi** [comment] 2017-01-05 03:15
This should be fixed with the latest changes. Since I can't update the PPA, let me know if you need help getting it installed. Maybe I'll put a link to download a .deb file that doesn't include icon/launcher from my site.

**Closed by thejambi** 2017-01-05 03:15 UTC

**Comment by thejambi** [comment] 2017-01-05 03:40
Link to latest changes with the subfolders and whatnot available from https://burnsoftware.wordpress.com/p-s-notes/ - see the section after the PPA details.

**Comment by bexelbie** [comment] 2017-01-05 12:32
Thanks for fixing this.  I was using test data so nothing was lost.

I am running Fedora, so the .deb and PPA aren't critical for me, but I can see them being critical for other users.

I built the program from source and if I continue to use it will work on packaging it for Fedora to accompany the other distributions.
